apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  labels:
    app: rpc-app
  spec:
    ports:
      port: 8081
      targetPort: 8081
    selector:
      app: rpc-app
    type: LoadBalancer
